AllCops:
  TargetRubyVersion: 2.4

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: simple_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: simple_quotes

Layout/LineLength:
  Max: 120
